### ISSUE TITLE
How can i get incppect current RX and TX ?

### ISSUE THREAD

**Issue by Eragon-Brisingr** [ggerganov/incppect#6]
I want to display imgui web app current RX and TX, is some way get it?

* TX:transport
* RX:receive

**Comment by ggerganov** [comment]
I just added per-client tx/rx stats. Check the `client-info` example about how to use it:

https://github.com/ggerganov/incppect/tree/master/examples/client-info

**Comment by Eragon-Brisingr** [comment]
Thanks~

**Comment by Eragon-Brisingr** [comment]
int32 will overflow when over 1gb, maybe use double is better ?
